# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('code_suffix', models.CharField(max_length=10)),
                ('performance_measure', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('debit_code', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('scheduled_start_date', models.DateField()),
                ('scheduled_end_date', models.DateField()),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('projected_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('budgeted_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('projected_end_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budgeted_manhours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('projected_manhours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actual_manhours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='file/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='file/')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('result', models.CharField(max_length=100)),
                ('objective_commentary', models.TextField(default='Explanation')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('is_initiative_manager', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpdashboard.Department')),
                ('designation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cpdashboard.Designation', verbose_name='Job Title')),
                ('initiatives', models.ManyToManyField(to='cpdashboard.Initiative')),
            ],
        ),
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpdashboard.Company')),
            ],
        ),
        migrations.AddField(
            model_name='objective',
            name='perspective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpdashboard.Perspective'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpdashboard.Objective'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpdashboard.Industry'),
        ),
        migrations.AddField(
            model_name='comment',
            name='initiative',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='cpdashboard.Initiative'),
        ),
    ]
